# build stage
FROM golang:1.23-bookworm AS build

WORKDIR /app

COPY ./go.mod ./go.sum ./

RUN go mod download

COPY ./ ./

RUN go build -o ./app ./cmd/main.go

# unit test stage
# Run the tests in the container
# can run it by using "docker build -f Dockerfile.test -t git-ops-go --progress plain 
# --no-cache --target run-unit-tests ."
FROM build AS run-unit-tests
RUN go test -v ./...
