name: Build and Push Docker Container

on:
  workflow_run:
    workflows: ["Build Docker Image and Run Unit Tests"] # Name of the workflow file to wait for
    types:
      - completed # Trigger when the "Build Docker Image and Run Unit Tests" workflow finishes

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/my-repo:git-ops-go

        
          # Attestations
          # SBOM (Software Bill of Materials) and provenance attestations improve security and traceability, ensuring your images meet modern software supply chain requirements.
          # With a small amount of additional configuration, you can configure docker/build-push-action to generate Software Bill of Materials (SBOM) and provenance attestations for the image, at build-time.
          # To generate this additional metadata, you need to make two changes to your workflow:
          # Before the build step, add a step that uses docker/setup-buildx-action. This action configures your Docker build client with additional capabilities that the default client doesn't support.
          # Then, update the Build and push Docker image step to also enable SBOM and provenance attestations.
          # annotations: ${{ steps.meta.outputs.annotations }}
          # provenance: true
          # sbom: true